version: '3.5'
services:
  ros-bridge:
    image: gramaziokohler/ros-abb-planner:19.11
    container_name: ros-bridge-ppl
    environment:
      - "ROS_HOSTNAME=ros-bridge"
      - "ROS_MASTER_URI=http://ros-master-pp:11311"
    ports:
      - "9090:9090"
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - rosbridge_server
      - rosbridge_websocket.launch

  ros-fileserver:
    image: gramaziokohler/ros-abb-planner:19.11
    container_name: ros-fileserver
    environment:
      - ROS_HOSTNAME=ros-fileserver
      - ROS_MASTER_URI=http://ros-master-pp:11311
    # depends_on:
    #   - ros-master
    command:
      - roslaunch
      - --wait
      - file_server
      - file_server.launch

  gui:
    image: gramaziokohler/novnc:19.05
    ports:
      - "8080:8080"

  abb-tf-base_link:
    image: gramaziokohler/ros-abb-planner:19.11
    container_name: abb-tf-base_link
    environment:
      - ROS_HOSTNAME=abb-tf-base_link
      - ROS_MASTER_URI=http://ros-master:11311
    depends_on:
      - ros-master
    command:
      - rosrun
      - tf
      - static_transform_publisher
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '1'
      - world
      - base_link
      - '100'

  abb-description:
    image: gramaziokohler/ros-ur-planner:19.11
    container_name: abb-description
    environment:
      - ROS_HOSTNAME=abb-description
      - ROS_MASTER_URI=http://ros-master:11311
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - ur3_moveit_config
      - planning_context.launch
      - load_robot_description:=true

  abb-planner:
    image: gramaziokohler/ros-abb-planner:19.11
    container_name: abb-planner
    environment:
      - ROS_HOSTNAME=abb-planner
      - ROS_MASTER_URI=http://ros-master-pp:11311
      - DISPLAY=gui:0.0
    depends_on:
      - ros-master
      - gui
    command:
      - roslaunch
      - --wait
      - abb_irb4600_support
      - test_irb4600_60_205.launch

networks:
    default:
        name: ros-net
